type TicketEvent = enum {
  Issued: Ticket,
  Validated: u64,
  NotFound,
  Invalid,
};

type Ticket = struct {
  id: u64,
  event_name: str,
  place: str,
  date: str,
  price: u64,
  used: bool,
};

type IoTicketState = struct {
  id: u64,
  event_name: str,
  place: str,
  date: str,
  price: u64,
  used: bool,
};

constructor {
  New : ();
};

service TrafficLight {
  IssueTicket : (event_name: str, place: str, date: str, price: u64) -> TicketEvent;
  ValidateTicket : (ticket_id: u64) -> TicketEvent;
  query QueryTicket : (ticket_id: u64) -> opt IoTicketState;
};

